language: node_js
node_js:
- "12.18.4"

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node_modules/.bin/newman run gbook_test.postman_collection.json --env-var "apiKey=AIzaSyBZqLcuZjc-md5f55yCg1HPhsEwXYUaKKc" --env-var "dynamicToken=ya29.a0AfH6SMDAdeBpwEUB9pQGHyOaArRWRSfBy_dHdrTmCNubzSBC758ERMAn-SClS0yVQ1MyXrnScsuKv61r84UwGy2XVc4CJxyudv8I2u7UwVcp9a092sOH5JS6_E5iZahek2oMr0V-PND-sYY-VoVIGkncz3qSdg" -d gbook_test.postman_datas.json