language: node_js
node_js:
- "12.18.4"

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node_modules/.bin/newman run gbook_test.postman_collection.json -e gbook_test.postman_environment.json -d gbook_test.postman_datas.json