language: node_js
node_js:
- "12.18.4"

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node_modules/.bin/newman run gbook_test.postman_collection.json --env-var "apiKey=AIzaSyBZqLcuZjc-md5f55yCg1HPhsEwXYUaKKc" --env-var "dynamicToken=ya29.a0AfH6SMDWGfCkzx6JGtOZsWGZZCy4RlUZCJ5HQTcQ8pddggThYZcW1YWOF4YAxCPQU9p5-B5qaTFHSfLm50q6MDZrG1n0yaXyz-waHPo4JW-zgmQ54vXYUQrtX8f13oLRAVbspulhFMu-NvjJ6hCRU8EF9m4Rzw" -d gbook_test.postman_datas.json